---
- name: Install required package
  ansible.builtin.package:
    name: cifs-utils
    state: present
  become: true

- name: Configure NetworkManager to wait for connection
  ansible.builtin.systemd:
    name: NetworkManager-wait-online
    enabled: true
  become: true

- name: Put cifspw file in place
  ansible.builtin.template:
    src: cifspw.jinja2
    dest: /etc/cifspw
    owner: "{{ nas_mounts_os_user }}"
    group: root
    mode: "0600"
  become: true

- name: Ensure cifs mounts
  ansible.posix.mount:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: cifs
    opts: "auto,users,_netdev,uid={{ nas_mounts_os_user }},gid={{ nas_mounts_os_user }},credentials=/etc/cifspw,vers=3,x-gvfs-show,x-gvfs-name={{ item.name | default(item.dest | basename, true) | urlencode }}"
    state: mounted
  loop: "{{ nas_mounts_cifs_mounts }}"
  become: true
